name: Docker Build Test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Backend
      run: docker build -t underscore-backend -f backend/Dockerfile .
      
    - name: Build Frontend
      run: docker build -t underscore-frontend -f frontend/Dockerfile .
